name: nopark
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    
  google_fonts: ^6.1.0
  dynamic_color: ^1.6.6
  geolocator: ^14.0.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  url_launcher: ^6.3.1
  firebase_auth:
  shared_preferences: ^2.5.3
  flutter_secure_storage:
  responsive_sizer: ^3.3.1
  smooth_page_indicator:
  intl:
  flutter_map:
  latlong2:
  permission_handler: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/main_logo.png
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 300
          style: italic
    - family: B612
      fonts:
        - asset: assets/fonts/B612-Regular.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/B612-Bold.ttf
          weight: 700
        - asset: assets/fonts/B612-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/B612-BoldItalic.ttf
          weight: 700
          style: italic

