name: nOPark
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nOPark
    volumes:
      - dbdata:/var/lib/postgresql/data

  osm_setup:
    build:
      context: .
      dockerfile: osm/osm_setup.Dockerfile
    depends_on:
      - db
    volumes:
      - ./data:/data
      - ./osm:/osm
    environment:
      - OSM_IMPORT_MODE=raw # raw or saved
    restart: "no" # This is a one-off init job, don't restart it.

  obj:
    image: minio/minio
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - objdata:/data
    command: server /data --console-address ":9001"

  obj_buckets:
    image: minio/mc
    depends_on:
      - obj
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://obj:9000 minio minio123;
      /usr/bin/mc mb myminio/users;
      /usr/bin/mc mb myminio/maps;
      /usr/bin/mc anonymous set public myminio/maps;
      exit 0;
      "

volumes:
  dbdata:
  objdata:
