name: nOPark
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nOPark
    volumes:
      - dbdata:/var/lib/postgresql/data

  db_admin:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tileserv:
    image: pramsey/pg_tileserv:latest
    restart: always
    ports:
      - 7800:7800
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nOPark
    depends_on:
      - db
      - osm2pgsql

  osm2pgsql:
    build:
      context: .
      dockerfile: db-importer.Dockerfile
    depends_on:
      - db
      - data
    volumes:
      - ./data:/data
    restart: "no" # This is a one-off import job, don't restart it.

  data:
    image: alpine/curl
    volumes:
      - ./data:/data
    command: >
      /bin/sh -c "
      apk add --no-cache curl;
      if [ ! -f /data/melbourne-latest.osm.pbf ]; then
        echo 'Downloading Melbourne OSM data...';
        curl -o /data/melbourne-latest.osm.pbf 'https://download.bbbike.org/osm/bbbike/Melbourne/Melbourne.osm.pbf';
      fi;
      exit 0;
      "
    restart: "no" # This is a one-off download job, don't restart it.

  obj:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - objdata:/data
    command: server /data --console-address ":9001"

  obj_buckets:
    image: minio/mc
    depends_on:
      - obj
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://obj:9000 minio minio123;
      /usr/bin/mc mb myminio/users;
      /usr/bin/mc mb myminio/maps;
      /usr/bin/mc anonymous set public myminio/maps;
      exit 0;
      "

volumes:
  dbdata:
  objdata:
