// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvWtaPGybvucaEu92j1ZLlyZru1unVUfI',
    appId: '1:849402733925:web:7126a586fa87ec3ebb2d8c',
    messagingSenderId: '849402733925',
    projectId: 'nopark-3162',
    authDomain: 'nopark-3162.firebaseapp.com',
    storageBucket: 'nopark-3162.firebasestorage.app',
    measurementId: 'G-4Y7B5Y1SGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__BkwmdksRKzxj0EQlbXttmBGzfIp2KU',
    appId: '1:849402733925:android:d8eac6417914b4f2bb2d8c',
    messagingSenderId: '849402733925',
    projectId: 'nopark-3162',
    storageBucket: 'nopark-3162.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKdWuU18PljeEXVPqNkAOhuUZrLffWqwY',
    appId: '1:849402733925:ios:3892a08382ff602cbb2d8c',
    messagingSenderId: '849402733925',
    projectId: 'nopark-3162',
    storageBucket: 'nopark-3162.firebasestorage.app',
    iosBundleId: 'com.example.nopark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvWtaPGybvucaEu92j1ZLlyZru1unVUfI',
    appId: '1:849402733925:web:fecf5d382e2d7ac5bb2d8c',
    messagingSenderId: '849402733925',
    projectId: 'nopark-3162',
    authDomain: 'nopark-3162.firebaseapp.com',
    storageBucket: 'nopark-3162.firebasestorage.app',
    measurementId: 'G-6MKLECC5PC',
  );
}
